CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    enabled BOOLEAN
);

CREATE TABLE IF NOT EXISTS users_roles (
    id SERIAL PRIMARY KEY,
    users_id INT NOT NULL,
    roles_id INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE
);

INSERT INTO roles (name) VALUES
('ROLE_ADMIN'),
('ROLE_PUBLISHER'),
('ROLE_USER'),
('ROLE_BAN');

ALTER TABLE users
ADD COLUMN claim_token VARCHAR(255) UNIQUE,
ADD COLUMN user_creator INT,
ADD COLUMN token_expiration TIMESTAMP;